/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AgencyIndexRouteImport } from './routes/agency.index'
import { Route as TrackerV1DotjsRouteImport } from './routes/tracker.v1[.]js'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AgencyNewClientRouteImport } from './routes/agency.new-client'
import { Route as AgencyAccountRouteImport } from './routes/agency.account'
import { Route as ApiPublicLeadsCollectRouteImport } from './routes/api/public/leads/collect'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AgencyIndexRoute = AgencyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencyRoute,
} as any)
const TrackerV1DotjsRoute = TrackerV1DotjsRouteImport.update({
  id: '/tracker/v1.js',
  path: '/tracker/v1.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AgencyNewClientRoute = AgencyNewClientRouteImport.update({
  id: '/new-client',
  path: '/new-client',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyAccountRoute = AgencyAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AgencyRoute,
} as any)
const ApiPublicLeadsCollectRoute = ApiPublicLeadsCollectRouteImport.update({
  id: '/api/public/leads/collect',
  path: '/api/public/leads/collect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agency/account': typeof AgencyAccountRoute
  '/agency/new-client': typeof AgencyNewClientRoute
  '/app/account': typeof AppAccountRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/tracking': typeof AppTrackingRoute
  '/tracker/v1.js': typeof TrackerV1DotjsRoute
  '/agency/': typeof AgencyIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/leads/collect': typeof ApiPublicLeadsCollectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agency/account': typeof AgencyAccountRoute
  '/agency/new-client': typeof AgencyNewClientRoute
  '/app/account': typeof AppAccountRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/tracking': typeof AppTrackingRoute
  '/tracker/v1.js': typeof TrackerV1DotjsRoute
  '/agency': typeof AgencyIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/leads/collect': typeof ApiPublicLeadsCollectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency': typeof AgencyRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agency/account': typeof AgencyAccountRoute
  '/agency/new-client': typeof AgencyNewClientRoute
  '/app/account': typeof AppAccountRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/tracking': typeof AppTrackingRoute
  '/tracker/v1.js': typeof TrackerV1DotjsRoute
  '/agency/': typeof AgencyIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/leads/collect': typeof ApiPublicLeadsCollectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency'
    | '/app'
    | '/login'
    | '/signup'
    | '/agency/account'
    | '/agency/new-client'
    | '/app/account'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/pipeline'
    | '/app/tracking'
    | '/tracker/v1.js'
    | '/agency/'
    | '/app/'
    | '/api/public/leads/collect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/agency/account'
    | '/agency/new-client'
    | '/app/account'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/pipeline'
    | '/app/tracking'
    | '/tracker/v1.js'
    | '/agency'
    | '/app'
    | '/api/public/leads/collect'
  id:
    | '__root__'
    | '/'
    | '/agency'
    | '/app'
    | '/login'
    | '/signup'
    | '/agency/account'
    | '/agency/new-client'
    | '/app/account'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/pipeline'
    | '/app/tracking'
    | '/tracker/v1.js'
    | '/agency/'
    | '/app/'
    | '/api/public/leads/collect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyRoute: typeof AgencyRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TrackerV1DotjsRoute: typeof TrackerV1DotjsRoute
  ApiPublicLeadsCollectRoute: typeof ApiPublicLeadsCollectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/agency/': {
      id: '/agency/'
      path: '/'
      fullPath: '/agency/'
      preLoaderRoute: typeof AgencyIndexRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/tracker/v1.js': {
      id: '/tracker/v1.js'
      path: '/tracker/v1.js'
      fullPath: '/tracker/v1.js'
      preLoaderRoute: typeof TrackerV1DotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/agency/new-client': {
      id: '/agency/new-client'
      path: '/new-client'
      fullPath: '/agency/new-client'
      preLoaderRoute: typeof AgencyNewClientRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/account': {
      id: '/agency/account'
      path: '/account'
      fullPath: '/agency/account'
      preLoaderRoute: typeof AgencyAccountRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/api/public/leads/collect': {
      id: '/api/public/leads/collect'
      path: '/api/public/leads/collect'
      fullPath: '/api/public/leads/collect'
      preLoaderRoute: typeof ApiPublicLeadsCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgencyRouteChildren {
  AgencyAccountRoute: typeof AgencyAccountRoute
  AgencyNewClientRoute: typeof AgencyNewClientRoute
  AgencyIndexRoute: typeof AgencyIndexRoute
}

const AgencyRouteChildren: AgencyRouteChildren = {
  AgencyAccountRoute: AgencyAccountRoute,
  AgencyNewClientRoute: AgencyNewClientRoute,
  AgencyIndexRoute: AgencyIndexRoute,
}

const AgencyRouteWithChildren =
  AgencyRoute._addFileChildren(AgencyRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyRoute: AgencyRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TrackerV1DotjsRoute: TrackerV1DotjsRoute,
  ApiPublicLeadsCollectRoute: ApiPublicLeadsCollectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
